services:
  ups-monitor:
    build: .
    container_name: ${SERVER_NAME}
    devices:
      - /dev/ttyUSB0:/dev/ttyTSSHARA0
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
    # Mapeamento local do código fonte, só descomentar caso for necessário codar/debugar o código.
    #volumes:
    #  - ./ups_tsshara_monitor:/app/ups_tsshara_monitor
    restart: unless-stopped