services:
  # Instância Base do Monitor
  ups-monitor:
    build: .
    container_name:  ups_monitor_iluminacao
    devices:
      - /dev/ttyUSB0:/dev/ttyTSSHARA0
    env_file: ".env"
    # Mapeamento local do código fonte, só descomentar caso for necessário codar/debugar o código.
    #volumes:
    #  - ./ups_tsshara_monitor:/app/ups_tsshara_monitor
    restart: unless-stopped
    # Mapeamento local do código fonte, só descomentar caso for necessário codar/debugar o código.
    #volumes:
    #  - ./ups_tsshara_monitor:/app/ups_tsshara_monitor
    restart: unless-stopped